### ISSUE TITLE
Can't get access to data from the data folder

### ISSUE THREAD

**Issue by SilencerWeb** [netlify-templates/victor-hugo#177]
**- Do you want to request a *feature* or report a *bug*?**
A bug

**- What is the current behavior?**
Right now I have file `site/data/pages/index.yml`. I'm trying to get data from this file inside `site/layouts/index.html`.

Here is my `site/data/pages/index.yml`:
```yaml
mainNavLinks:
  - text: "Features"
    url: "#features"
    shouldBeOpenInNewWindow: false
  - text: "IAC"
    url: "#iac"
    shouldBeOpenInNewWindow: false
  - text: "Integrations"
    url: "#integrations"
    shouldBeOpenInNewWindow: false
  - text: "Contact us"
    url: "#contact-us"
    shouldBeOpenInNewWindow: false
  - text: "Documentation"
    url: "#documentation"
    shouldBeOpenInNewWindow: true
  - text: "Blog"
    url: "#blog"
    shouldBeOpenInNewWindow: true
```

Here is my `site/layouts/index.html`:
```go
{{ range $.Site.Data.pages.index.mainNavLinks }}
  <li class="main-nav__item"><a class="main-nav__link" href="{{ .url }}">{{ .text }}</a></li>
{{ end }}
```

Here is my command line after running `yarn start`:
![image](https://user-images.githubusercontent.com/20713191/57770300-6b5afb80-7729-11e9-8b95-573d65f50d38.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a file `site/data/pages/index.yml`.
2. Add this code to  `site/layouts/index.html`:
```go
{{ range $.Site.Data.pages.index.mainNavLinks }}
  <li class="main-nav__item"><a class="main-nav__link" href="{{ .url }}">{{ .text }}</a></li>
{{ end }}
```

**- What is the expected behavior?**
It should render all elements on the page

**- Please mention your node.js, NPM, Hugo and operating system version.**
node.js: v11.7.0
NPM: 6.9.0
Hugo: Hugo Static Site Generator v0.55.3/extended darwin/amd64 BuildDate: unknown
